# 1. [开启zookeeper集群](https://github.com/xiao-ren-wu/docker-compose-storage/blob/main/zookeeper-docker-compose.yml)
# 2. 将127.0.0.1IP替换成本地ip
# 3. 开启后，访问localhost:9000即可看到卡夫卡监控页面
version: '3.2'
services:
  kafka1:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
     volumes:
      - /home/myhome/kafka1:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181, 127.0.0.1:2182, 127.0.0.1:2183
      KAFKA_ADVERTISED_PORT: 9092
    container_name: kafka1
  kafka2:
    image: wurstmeister/kafka
    ports:
      - 9093:9092
     volumes:
      - /home/myhome/kafka1:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9093
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181, 127.0.0.1:2182, 127.0.0.1:2183
      KAFKA_ADVERTISED_PORT: 9093
    container_name: kafka2
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: 127.0.0.1
    ports:
      - 9000:9000
