version: '3.3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.10.220
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ~/kafka:/kafka
      - ~/kafka/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9999:9000
    environment:
      ZK_HOSTS: zookeeper:2181
